set(COMPILER_PATH "${CMAKE_CURRENT_LIST_DIR}/multicompiler/tools/bin")
set(CMAKE_C_COMPILER "${COMPILER_PATH}/clang")
set(CMAKE_CXX_COMPILER "${COMPILER_PATH}/clang")
set(CMAKE_LINKER "${COMPILER_PATH}/ld")
set(CMAKE_CXX_LINK_EXECUTABLE "<CMAKE_LINKER> <FLAGS> <CMAKE_CXX_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")
set(CMAKE_C_LINK_EXECUTABLE "<CMAKE_LINKER> <FLAGS> <CMAKE_C_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")

set(CMAKE_C_COMPILER_WORKS 1)
set(CMAKE_CXX_COMPILER_WORKS 1)
