#!/usr/bin/env python

import sys
import json

if __name__ == "__main__":
  OUTPUT_FILE = "combined.json"
  output = {}
  num_files = 0
  for file_name in sys.argv[1:]:
    with open(file_name, "r") as fp:
      num_files += 1
      current_stats = json.load(fp)
      for key in current_stats:
        if key in output:
          output[key] += current_stats[key]
        else:
          output[key] = current_stats[key]
    with open(OUTPUT_FILE, "w+") as fp:
      json.dump(output, fp, indent=1)
  print("Combined {0} files. Wrote output to: {1}".format(num_files, OUTPUT_FILE))
 
